// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Data.Context;

#nullable disable

namespace StudentManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529133120_CreateDuyuruOkumalarTable")]
    partial class CreateDuyuruOkumalarTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.BelgeTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<string>("BelgeDosyaAdi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BelgeDosyaYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BelgeTur")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("IslemYapanId")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<string>("SonucNotu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.HasIndex("IsActive");

                    b.HasIndex("IslemYapanId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("BelgeTalepleri", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Bolum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BolumKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Fakulte")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinMezuniyetAkts")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolumKodu")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Bolumler", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Akts")
                        .HasColumnType("int");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kredi")
                        .HasColumnType("int");

                    b.Property<int>("MaxKontenjan")
                        .HasColumnType("int");

                    b.Property<int>("TeoriSaat")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UygulamaSaat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolumId");

                    b.HasIndex("DersKodu")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Dersler", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.DersAtama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<string>("Derslik")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DonemId")
                        .HasColumnType("int");

                    b.Property<int?>("Gun")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KayitliOgrenciSayisi")
                        .HasColumnType("int");

                    b.Property<int>("OgretmenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonemId");

                    b.HasIndex("IsActive");

                    b.HasIndex("OgretmenId");

                    b.HasIndex("DersId", "DonemId")
                        .IsUnique();

                    b.ToTable("DersAtamalar", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Donem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DersKayitBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DersKayitBitis")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonemAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DonemKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DonemTur")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi");

                    b.HasIndex("DonemKodu")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Donemler", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Duyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Hedef")
                        .HasColumnType("int");

                    b.Property<int?>("HedefBolumId")
                        .HasColumnType("int");

                    b.Property<int?>("HedefDersAtamaId")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Onemli")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("YayinTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("YayinlayanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hedef");

                    b.HasIndex("HedefBolumId");

                    b.HasIndex("HedefDersAtamaId");

                    b.HasIndex("IsActive");

                    b.HasIndex("YayinlayanId");

                    b.ToTable("Duyurular", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.DuyuruOkuma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DuyuruId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OkunmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DuyuruId");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("OgrenciId", "DuyuruId")
                        .IsUnique();

                    b.ToTable("DuyuruOkumalar", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BolumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastPasswordChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unvan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolumId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.HasIndex("Rol");

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AktifDonemId")
                        .HasColumnType("int");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<decimal?>("Gano")
                        .HasColumnType("decimal(4,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilFotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SinifSeviyesi")
                        .HasColumnType("int");

                    b.Property<int>("TamamlananAkts")
                        .HasColumnType("int");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AktifDonemId");

                    b.HasIndex("BolumId");

                    b.HasIndex("IsActive");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.HasIndex("OgrenciNo")
                        .IsUnique();

                    b.ToTable("Ogrenciler", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.OgrenciDers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ButunlemeNotu")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DersAtamaId")
                        .HasColumnType("int");

                    b.Property<int>("DevamSayisi")
                        .HasColumnType("int");

                    b.Property<int>("DevamsizlikSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("DonemId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalNotu")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool?>("GectiMi")
                        .HasColumnType("bit");

                    b.Property<decimal?>("GenelNot")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("HarfNotu")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NotKatsayisi")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OnaylayanKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("RedNedeni")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("VizeNotu")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("DersAtamaId");

                    b.HasIndex("DonemId");

                    b.HasIndex("Durum");

                    b.HasIndex("IsActive");

                    b.HasIndex("OnaylayanKullaniciId");

                    b.HasIndex("OgrenciId", "DersAtamaId")
                        .IsUnique();

                    b.ToTable("OgrenciDersler", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.OgrenciYoklama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Geldi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("YoklamaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("YoklamaId", "OgrenciId")
                        .IsUnique();

                    b.ToTable("OgrenciYoklamalar", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Sinav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DersAtamaId")
                        .HasColumnType("int");

                    b.Property<string>("Derslik")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SinavTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SinavTur")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SinavTarihi");

                    b.HasIndex("DersAtamaId", "SinavTur");

                    b.ToTable("Sinavlar", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Yoklama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DersAtamaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OgretmenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("YoklamaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OgretmenId");

                    b.HasIndex("DersAtamaId", "YoklamaTarihi");

                    b.ToTable("Yoklamalar", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("AuditLogs")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.BelgeTalebi", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.Kullanici", "IslemYapan")
                        .WithMany()
                        .HasForeignKey("IslemYapanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentManagement.Core.Entities.Ogrenci", "Ogrenci")
                        .WithMany("BelgeTalepleri")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IslemYapan");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Ders", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.Bolum", "Bolum")
                        .WithMany("Dersler")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.DersAtama", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.Ders", "Ders")
                        .WithMany("DersAtamalari")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagement.Core.Entities.Donem", "Donem")
                        .WithMany("DersAtamalari")
                        .HasForeignKey("DonemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagement.Core.Entities.Kullanici", "Ogretmen")
                        .WithMany("DersAtamalari")
                        .HasForeignKey("OgretmenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Donem");

                    b.Navigation("Ogretmen");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Duyuru", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.Bolum", "HedefBolum")
                        .WithMany()
                        .HasForeignKey("HedefBolumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentManagement.Core.Entities.DersAtama", "HedefDersAtama")
                        .WithMany("Duyurular")
                        .HasForeignKey("HedefDersAtamaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentManagement.Core.Entities.Kullanici", "Yayinlayan")
                        .WithMany("Duyurular")
                        .HasForeignKey("YayinlayanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HedefBolum");

                    b.Navigation("HedefDersAtama");

                    b.Navigation("Yayinlayan");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.DuyuruOkuma", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.Duyuru", "Duyuru")
                        .WithMany()
                        .HasForeignKey("DuyuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Core.Entities.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duyuru");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Kullanici", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.Bolum", "Bolum")
                        .WithMany("Ogretmenler")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Ogrenci", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.Donem", "AktifDonem")
                        .WithMany()
                        .HasForeignKey("AktifDonemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentManagement.Core.Entities.Bolum", "Bolum")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagement.Core.Entities.Kullanici", "Kullanici")
                        .WithOne("Ogrenci")
                        .HasForeignKey("StudentManagement.Core.Entities.Ogrenci", "KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AktifDonem");

                    b.Navigation("Bolum");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.OgrenciDers", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.DersAtama", "DersAtama")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("DersAtamaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagement.Core.Entities.Donem", null)
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("DonemId");

                    b.HasOne("StudentManagement.Core.Entities.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagement.Core.Entities.Kullanici", "OnaylayanKullanici")
                        .WithMany()
                        .HasForeignKey("OnaylayanKullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DersAtama");

                    b.Navigation("Ogrenci");

                    b.Navigation("OnaylayanKullanici");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.OgrenciYoklama", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentManagement.Core.Entities.Yoklama", "Yoklama")
                        .WithMany("OgrenciYoklamalar")
                        .HasForeignKey("YoklamaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Ogrenci");

                    b.Navigation("Yoklama");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Sinav", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.DersAtama", "DersAtama")
                        .WithMany("Sinavlar")
                        .HasForeignKey("DersAtamaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DersAtama");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Yoklama", b =>
                {
                    b.HasOne("StudentManagement.Core.Entities.DersAtama", "DersAtama")
                        .WithMany("Yoklamalar")
                        .HasForeignKey("DersAtamaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagement.Core.Entities.Kullanici", "Ogretmen")
                        .WithMany()
                        .HasForeignKey("OgretmenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DersAtama");

                    b.Navigation("Ogretmen");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Bolum", b =>
                {
                    b.Navigation("Dersler");

                    b.Navigation("Ogrenciler");

                    b.Navigation("Ogretmenler");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Ders", b =>
                {
                    b.Navigation("DersAtamalari");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.DersAtama", b =>
                {
                    b.Navigation("Duyurular");

                    b.Navigation("OgrenciDersler");

                    b.Navigation("Sinavlar");

                    b.Navigation("Yoklamalar");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Donem", b =>
                {
                    b.Navigation("DersAtamalari");

                    b.Navigation("OgrenciDersler");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("DersAtamalari");

                    b.Navigation("Duyurular");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Ogrenci", b =>
                {
                    b.Navigation("BelgeTalepleri");

                    b.Navigation("OgrenciDersler");
                });

            modelBuilder.Entity("StudentManagement.Core.Entities.Yoklama", b =>
                {
                    b.Navigation("OgrenciYoklamalar");
                });
#pragma warning restore 612, 618
        }
    }
}
